# -*- coding: utf-8 -*-
"""경남빅데이터공모ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iq7M1a9OZNJRKZFlHwLHYu8FtObBBkQj
"""

from google.colab import files
uploaded = files.upload()  # 실행하면 파일 선택창 뜸

pip install openpyxl requests

KAKAO_API_KEY = "00000000"

import requests
import pandas as pd
import time

# ── 1. API 키 입력 ──────────────────────────────
KAKAO_API_KEY = "0000000"

# ── 2. 엑셀 불러오기 ────────────────────────────
df = pd.read_excel("경남_의료기관_통합_데이터.xlsx", sheet_name="통합")
print(f"총 {len(df)}개 기관 불러오기 완료")
print(df.head())

# ── 3. 지오코딩 함수 ────────────────────────────
def get_coords(address):
    if pd.isna(address) or str(address).strip() == "":
        return None, None

    # 주소 앞에 경상남도 붙이기 (없으면)
    addr = str(address).strip()
    if not addr.startswith("경상남도") and not addr.startswith("경남"):
        addr = "경상남도 " + addr

    url = "https://dapi.kakao.com/v2/local/search/address.json"
    headers = {"Authorization": f"KakaoAK {KAKAO_API_KEY}"}
    params = {"query": addr}

    try:
        res = requests.get(url, headers=headers, params=params)
        result = res.json()

        if result["documents"]:
            lat = float(result["documents"][0]["y"])
            lng = float(result["documents"][0]["x"])
            return lat, lng
        else:
            return None, None
    except Exception as e:
        print(f"오류: {addr} → {e}")
        return None, None

# ── 4. 전체 실행 ────────────────────────────────
# 달빛어린이병원, 심야약국, 응급의료기관, 보건소 먼저 (99개)
# 일반약국은 시간 걸려서 나중에
priority = df[df["구분"] != "일반약국"].copy()
general = df[df["구분"] == "일반약국"].copy()

print(f"\n우선 처리: {len(priority)}개 (달빛·심야약국·응급·보건소)")
print("지오코딩 시작...\n")

lats, lngs = [], []
for i, row in priority.iterrows():
    lat, lng = get_coords(row["주소"])
    lats.append(lat)
    lngs.append(lng)

    # 진행상황 출력
    if (len(lats)) % 10 == 0:
        print(f"  {len(lats)}/{len(priority)} 완료...")

    time.sleep(0.1)  # API 과호출 방지

priority["위도"] = lats
priority["경도"] = lngs

# 결과 확인
success = priority["위도"].notna().sum()
print(f"\n완료! {success}/{len(priority)}개 좌표 변환 성공")
print(priority[["구분","시군","기관명","위도","경도"]].head(10))

# ── 5. 일반약국 지오코딩 (선택) ─────────────────
print("\n일반약국 지오코딩 시작... (1,321개, 약 3~4분 소요)")
lats2, lngs2 = [], []
for i, row in general.iterrows():
    lat, lng = get_coords(row["주소"])
    lats2.append(lat)
    lngs2.append(lng)

    if len(lats2) % 100 == 0:
        print(f"  {len(lats2)}/{len(general)} 완료...")

    time.sleep(0.05)

general["위도"] = lats2
general["경도"] = lngs2

# ── 6. 합치고 저장 ──────────────────────────────
result = pd.concat([priority, general], ignore_index=True)

result.to_excel("경남_의료기관_좌표완성.xlsx", index=False)
print("\n✅ 저장 완료: 경남_의료기관_좌표완성.xlsx")

# 시군별 좌표 변환 성공률 확인
print("\n시군별 좌표 변환 현황:")
summary = result.groupby("시군")["위도"].apply(lambda x: f"{x.notna().sum()}/{len(x)}")
print(summary.to_string())

# 코랩 마지막 셀에 추가
from google.colab import files
files.download("경남_의료기관_좌표완성.xlsx")

!pip install geopandas -q

import geopandas as gpd

# 경남 경계 다운로드
import urllib.request
url = "https://raw.githubusercontent.com/southkorea/southkorea-maps/master/kostat/2018/json/skorea-municipalities-2018-geo.json"
gdf = gpd.read_file(url)

# 경남만 필터링
gyeongnam = gdf[gdf['name'].str.contains('경상남도|창원|진주|통영|사천|김해|밀양|거제|양산|의령|함안|창녕|고성|남해|하동|산청|함양|거창|합천')]
gyeongnam.to_file("경남_경계.shp")
print("완료!")

from google.colab import files
files.download("경남_경계.shp")

from google.colab import files
files.download("경남_경계.shp")
files.download("경남_경계.dbf")
files.download("경남_경계.shx")
files.download("경남_경계.prj")
files.download("경남_경계.cpg")

from google.colab import files
uploaded = files.upload()

import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

# 폰트 설치 및 적용
import subprocess
subprocess.run(['apt-get', 'install', '-y', 'fonts-nanum'], capture_output=True)
fe = fm.FontEntry(fname='/usr/share/fonts/truetype/nanum/NanumGothic.ttf', name='NanumGothic')
fm.fontManager.ttflist.insert(0, fe)
plt.rcParams['font.family'] = 'NanumGothic'

# 경남 경계 - code 대신 name으로 필터링
url = "https://raw.githubusercontent.com/southkorea/southkorea-maps/master/kostat/2018/json/skorea-municipalities-2018-geo.json"
gdf_all = gpd.read_file(url)
print("컬럼:", gdf_all.columns.tolist())
print("샘플:", gdf_all[['name','code']].head(10).to_string())

print(gdf_all[gdf_all['name'].str.contains('창원|진주|통영|김해|거제|양산|밀양|사천|의령|함안|창녕|고성|남해|하동|산청|함양|거창|합천')][['name','code']].to_string())

import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import subprocess

# 폰트
subprocess.run(['apt-get', 'install', '-y', 'fonts-nanum'], capture_output=True)
fe = fm.FontEntry(fname='/usr/share/fonts/truetype/nanum/NanumGothic.ttf', name='NanumGothic')
fm.fontManager.ttflist.insert(0, fe)
plt.rcParams['font.family'] = 'NanumGothic'

# 경남 경계
url = "https://raw.githubusercontent.com/southkorea/southkorea-maps/master/kostat/2018/json/skorea-municipalities-2018-geo.json"
gdf_all = gpd.read_file(url)
gyeongnam = gdf_all[gdf_all['code'].str.startswith('38')].to_crs("EPSG:4326")
print("경남 시군 수:", len(gyeongnam))

# 의료기관 데이터
df = pd.read_csv("경남_의료기관_좌표완성.csv")
df = df.dropna(subset=['위도','경도'])
gdf = gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df.경도, df.위도), crs="EPSG:4326")

# 지도 그리기
colors = {
    '달빛어린이병원': ('blue', '*', 200),
    '심야약국': ('orange', 'o', 80),
    '응급의료기관': ('red', '^', 100),
    '보건소': ('green', 's', 80),
    '일반약국': ('gray', '.', 20),
}

fig, ax = plt.subplots(figsize=(12, 12))
gyeongnam.plot(ax=ax, color='lightyellow', edgecolor='black', linewidth=1)

for 구분, (color, marker, size) in colors.items():
    subset = gdf[gdf['구분'] == 구분]
    subset.plot(ax=ax, color=color, marker=marker, markersize=size, label=구분)

plt.legend(loc='lower left', fontsize=12)
plt.title("경남 야간·휴일 의료기관 분포", fontsize=16)
plt.axis('off')
plt.savefig("경남_의료기관_지도.png", dpi=150, bbox_inches='tight')
plt.show()
print("저장완료!")

from google.colab import files
files.download("경남_의료기관_지도.png")

!pip install geopandas shapely -q

import geopandas as gpd
import pandas as pd
import numpy as np
from shapely.geometry import Point

# 의료기관 데이터
df = pd.read_csv("경남_의료기관_좌표완성.csv")
df = df.dropna(subset=['위도','경도'])

# 달빛어린이병원, 심야약국, 응급의료기관만 추출
target = df[df['구분'].isin(['달빛어린이병원','심야약국','응급의료기관','보건소'])]
target_gdf = gpd.GeoDataFrame(target, geometry=gpd.points_from_xy(target.경도, target.위도), crs="EPSG:4326").to_crs("EPSG:5179")

# 경남 경계
url = "https://raw.githubusercontent.com/southkorea/southkorea-maps/master/kostat/2018/json/skorea-municipalities-2018-geo.json"
gdf_all = gpd.read_file(url)
gyeongnam = gdf_all[gdf_all['code'].str.startswith('38')].to_crs("EPSG:5179")

# 경남 격자 생성 (1km)
from shapely.geometry import box
bounds = gyeongnam.total_bounds  # minx, miny, maxx, maxy
minx, miny, maxx, maxy = bounds
grid_size = 1000  # 1km

grid_cells = []
x = minx
while x < maxx:
    y = miny
    while y < maxy:
        grid_cells.append(box(x, y, x+grid_size, y+grid_size))
        y += grid_size
    x += grid_size

grid = gpd.GeoDataFrame(geometry=grid_cells, crs="EPSG:5179")

# 경남 영역만 남기기
grid = gpd.clip(grid, gyeongnam)
grid['center'] = grid.geometry.centroid
print(f"경남 격자 수: {len(grid)}개")

from shapely.ops import nearest_points

# 구분별 최근접 거리 계산 함수
def calc_min_distance(grid_gdf, facility_gdf, col_name):
    if len(facility_gdf) == 0:
        grid_gdf[col_name] = np.nan
        return grid_gdf

    facility_union = facility_gdf.geometry.unary_union
    distances = []
    for center in grid_gdf['center']:
        dist = center.distance(nearest_points(center, facility_union)[1])
        distances.append(dist / 1000)  # km 단위
    grid_gdf[col_name] = distances
    return grid_gdf

# 구분별 계산
print("달빛어린이병원 거리 계산 중...")
dalbit = target_gdf[target_gdf['구분'] == '달빛어린이병원']
grid = calc_min_distance(grid, dalbit, '달빛_거리km')

print("심야약국 거리 계산 중...")
simya = target_gdf[target_gdf['구분'] == '심야약국']
grid = calc_min_distance(grid, simya, '심야약국_거리km')

print("응급의료기관 거리 계산 중...")
eung = target_gdf[target_gdf['구분'] == '응급의료기관']
grid = calc_min_distance(grid, eung, '응급_거리km')

print("보건소 거리 계산 중...")
bk = target_gdf[target_gdf['구분'] == '보건소']
grid = calc_min_distance(grid, bk, '보건소_거리km')

print("\n완료!")
print(grid[['달빛_거리km','심야약국_거리km','응급_거리km','보건소_거리km']].describe())

# 취약도 점수 계산 (거리가 멀수록 취약)
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

cols = ['달빛_거리km','심야약국_거리km','응급_거리km','보건소_거리km']
grid[cols] = grid[cols].fillna(grid[cols].max())

# 정규화 후 가중치 적용
normalized = scaler.fit_transform(grid[cols])

# 가중치 (달빛어린이병원 30%, 심야약국 30%, 응급 25%, 보건소 15%)
weights = [0.30, 0.30, 0.25, 0.15]
grid['취약도점수'] = (normalized * weights).sum(axis=1)

print("취약도 점수 분포:")
print(grid['취약도점수'].describe())

# 지도 시각화
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

fe = fm.FontEntry(fname='/usr/share/fonts/truetype/nanum/NanumGothic.ttf', name='NanumGothic')
fm.fontManager.ttflist.insert(0, fe)
plt.rcParams['font.family'] = 'NanumGothic'

url = "https://raw.githubusercontent.com/southkorea/southkorea-maps/master/kostat/2018/json/skorea-municipalities-2018-geo.json"
gdf_all = gpd.read_file(url)
gyeongnam = gdf_all[gdf_all['code'].str.startswith('38')].to_crs("EPSG:5179")

fig, ax = plt.subplots(figsize=(12,12))
grid.plot(ax=ax, column='취약도점수', cmap='RdYlGn_r', legend=True,
          legend_kwds={'label':'취약도 점수', 'shrink':0.5})
gyeongnam.plot(ax=ax, color='none', edgecolor='black', linewidth=1.5)

plt.title("경남 야간·휴일 의료 취약도 지도", fontsize=16)
plt.axis('off')
plt.savefig("경남_취약도_지도.png", dpi=150, bbox_inches='tight')
plt.show()
print("저장완료!")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, GRU, Dense, Dropout

# 폰트
fe = fm.FontEntry(fname='/usr/share/fonts/truetype/nanum/NanumGothic.ttf', name='NanumGothic')
fm.fontManager.ttflist.insert(0, fe)
plt.rcParams['font.family'] = 'NanumGothic'

# 응급의학 전문의 수 데이터 (2016~2024)
data = {
    '연도': [2016,2017,2018,2019,2020,2021,2022,2023,2024],
    '전문의수': [48,48,54,59,66,71,74,79,86]
}
df = pd.DataFrame(data)

# 정규화
scaler = MinMaxScaler()
scaled = scaler.fit_transform(df[['전문의수']])

# 시퀀스 생성
def make_sequences(data, window=3):
    X, y = [], []
    for i in range(len(data)-window):
        X.append(data[i:i+window])
        y.append(data[i+window])
    return np.array(X), np.array(y)

X, y = make_sequences(scaled, window=3)
print(f"X shape: {X.shape}, y shape: {y.shape}")

# LSTM 모델
model = Sequential([
    LSTM(64, return_sequences=True, input_shape=(3,1)),
    Dropout(0.2),
    LSTM(32),
    Dropout(0.2),
    Dense(1)
])
model.compile(optimizer='adam', loss='mse')
model.summary()

# 학습
history = model.fit(X, y, epochs=200, batch_size=4, verbose=0)
print("학습 완료!")

# 2025~2030 예측
last_seq = scaled[-3:].reshape(1,3,1)
predictions = []
for _ in range(6):
    pred = model.predict(last_seq, verbose=0)
    predictions.append(pred[0][0])
    last_seq = np.append(last_seq[:,1:,:], pred.reshape(1,1,1), axis=1)

pred_original = scaler.inverse_transform(np.array(predictions).reshape(-1,1))
pred_years = list(range(2025, 2031))

print("\n예측 결과:")
for y, v in zip(pred_years, pred_original):
    print(f"  {y}년: {v[0]:.1f}명")

# 시각화
fig, ax = plt.subplots(figsize=(12,6))
ax.plot(df['연도'], df['전문의수'], 'bo-', linewidth=2, markersize=8, label='실제 데이터')
ax.plot(pred_years, pred_original, 'r^--', linewidth=2, markersize=8, label='LSTM 예측')
ax.axvline(x=2024.5, color='gray', linestyle='--', alpha=0.5)
ax.fill_between(pred_years,
                [v[0]*0.95 for v in pred_original],
                [v[0]*1.05 for v in pred_original],
                alpha=0.2, color='red', label='예측 범위')
ax.set_xlabel('연도', fontsize=13)
ax.set_ylabel('응급의학 전문의 수 (명)', fontsize=13)
ax.set_title('경상남도 응급의학 전문의 수 추세 및 LSTM 예측 (2016~2030)', fontsize=15)
ax.legend(fontsize=12)
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig("경남_전문의_예측.png", dpi=150, bbox_inches='tight')
plt.show()
print("저장완료!")

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import geopandas as gpd
import numpy as np

# 폰트
fe = fm.FontEntry(fname='/usr/share/fonts/truetype/nanum/NanumGothic.ttf', name='NanumGothic')
fm.fontManager.ttflist.insert(0, fe)
plt.rcParams['font.family'] = 'NanumGothic'

# 클러스터링 변수 준비
features = grid[['달빛_거리km','심야약국_거리km','응급_거리km','보건소_거리km']].fillna(0)
scaler2 = StandardScaler()
features_scaled = scaler2.fit_transform(features)

# 최적 클러스터 수 찾기 (엘보우 방법)
inertias = []
for k in range(2, 8):
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    km.fit(features_scaled)
    inertias.append(km.inertia_)

plt.figure(figsize=(8,4))
plt.plot(range(2,8), inertias, 'bo-')
plt.xlabel('클러스터 수')
plt.ylabel('이너셔')
plt.title('최적 클러스터 수 (엘보우)')
plt.grid(True, alpha=0.3)
plt.show()

# k=4로 클러스터링
km = KMeans(n_clusters=4, random_state=42, n_init=10)
grid['클러스터'] = km.fit_predict(features_scaled)

# 클러스터별 평균값
print("\n클러스터별 특성:")
print(grid.groupby('클러스터')[['달빛_거리km','심야약국_거리km','응급_거리km','보건소_거리km']].mean().round(1))

# 클러스터 이름 붙이기
cluster_names = {
    0: '양호지역',
    3: '보통지역',
    2: '취약지역',
    1: '최고취약지역'
}
grid['유형'] = grid['클러스터'].map(cluster_names)

# 경남 경계
url = "https://raw.githubusercontent.com/southkorea/southkorea-maps/master/kostat/2018/json/skorea-municipalities-2018-geo.json"
gdf_all = gpd.read_file(url)
gyeongnam = gdf_all[gdf_all['code'].str.startswith('38')].to_crs("EPSG:5179")

# 색상
color_map = {
    '양호지역': '#2ecc71',
    '보통지역': '#f1c40f',
    '취약지역': '#e67e22',
    '최고취약지역': '#e74c3c'
}

fig, ax = plt.subplots(figsize=(12,12))
for 유형, color in color_map.items():
    subset = grid[grid['유형'] == 유형]
    subset.plot(ax=ax, color=color, label=유형, alpha=0.8)

gyeongnam.plot(ax=ax, color='none', edgecolor='black', linewidth=1.5)
plt.legend(loc='lower left', fontsize=12, title='의료 취약 유형')
plt.title("경남 야간·휴일 의료 취약지 유형 분류", fontsize=16)
plt.axis('off')
plt.savefig("경남_클러스터_지도.png", dpi=150, bbox_inches='tight')
plt.show()
print("저장완료!")

import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

# 폰트
fe = fm.FontEntry(fname='/usr/share/fonts/truetype/nanum/NanumGothic.ttf', name='NanumGothic')
fm.fontManager.ttflist.insert(0, fe)
plt.rcParams['font.family'] = 'NanumGothic'

# 최고취약 + 취약지역만 추출
vulnerable = grid[grid['유형'].isin(['최고취약지역', '취약지역'])].copy()
print(f"취약 격자 수: {len(vulnerable)}개")

# 취약도 점수 높은 상위 5개 격자 중심점 = 최적 입지 후보
top5 = vulnerable.nlargest(5, '취약도점수').copy()
top5['center'] = top5.geometry.centroid
top5_gdf = gpd.GeoDataFrame(top5, geometry='center', crs="EPSG:5179").to_crs("EPSG:4326")

# 위경도 추출
top5_gdf['위도'] = top5_gdf.geometry.y
top5_gdf['경도'] = top5_gdf.geometry.x
print("\n최적 입지 후보 TOP5:")
print(top5_gdf[['취약도점수','달빛_거리km','심야약국_거리km','위도','경도']].to_string())

# 경남 경계
url = "https://raw.githubusercontent.com/southkorea/southkorea-maps/master/kostat/2018/json/skorea-municipalities-2018-geo.json"
gdf_all = gpd.read_file(url)
gyeongnam = gdf_all[gdf_all['code'].str.startswith('38')].to_crs("EPSG:5179")

# 시각화
color_map = {
    '양호지역': '#2ecc71',
    '보통지역': '#f1c40f',
    '취약지역': '#e67e22',
    '최고취약지역': '#e74c3c'
}

fig, ax = plt.subplots(figsize=(12,12))
for 유형, color in color_map.items():
    subset = grid[grid['유형'] == 유형]
    subset.plot(ax=ax, color=color, label=유형, alpha=0.7)

gyeongnam.plot(ax=ax, color='none', edgecolor='black', linewidth=1.5)

# TOP5 입지 표시
top5_plot = gpd.GeoDataFrame(top5, geometry='center', crs="EPSG:5179")
top5_plot.plot(ax=ax, color='blue', marker='★', markersize=300, zorder=5, label='최적 입지 후보')

for idx, (i, row) in enumerate(top5_plot.iterrows()):
    ax.annotate(f'  후보{idx+1}', xy=(row['center'].x, row['center'].y),
                fontsize=12, fontweight='bold', color='blue')

plt.legend(loc='lower left', fontsize=11, title='의료 취약 유형')
plt.title("경남 야간·휴일 의료기관 최적 입지 후보 TOP5", fontsize=16)
plt.axis('off')
plt.savefig("경남_최적입지.png", dpi=150, bbox_inches='tight')
plt.show()
print("저장완료!")

print(top5[['취약도점수','달빛_거리km']].to_string())
print("\ncenter 좌표:")
for i, row in top5.iterrows():
    print(f"  x={row['center'].x:.0f}, y={row['center'].y:.0f}")

print("\ngrid 전체 범위:")
print(f"  x: {grid['center'].apply(lambda g: g.x).min():.0f} ~ {grid['center'].apply(lambda g: g.x).max():.0f}")
print(f"  y: {grid['center'].apply(lambda g: g.y).min():.0f} ~ {grid['center'].apply(lambda g: g.y).max():.0f}")

print("\ngyeongnam 범위:")
print(gyeongnam.total_bounds)

# 후보 위치가 어느 시군인지 확인
top5_gdf2 = gpd.GeoDataFrame(top5, geometry='center', crs="EPSG:5179")
joined = gpd.sjoin(top5_gdf2, gyeongnam[['name','geometry']], how='left', predicate='within')
print(joined[['취약도점수','달빛_거리km','심야약국_거리km','name']].to_string())

# 통영 섬 제외하고 내륙 취약지역만 보기
# 최고취약지역 중 서북부 내륙만 추출
inland_vulnerable = grid[
    (grid['유형'].isin(['최고취약지역', '취약지역'])) &
    (grid['center'].apply(lambda g: g.y > 1650000))  # 남해안 섬 제외
].copy()

print(f"내륙 취약 격자 수: {len(inland_vulnerable)}개")

top5_inland = inland_vulnerable.nlargest(5, '취약도점수').copy()

# 시군 확인
top5_gdf3 = gpd.GeoDataFrame(top5_inland, geometry='center', crs="EPSG:5179")
joined2 = gpd.sjoin(top5_gdf3, gyeongnam[['name','geometry']], how='left', predicate='within')
print("\n내륙 최적 입지 후보 TOP5:")
print(joined2[['취약도점수','달빛_거리km','심야약국_거리km','name']].to_string())

fig, ax = plt.subplots(figsize=(12,12))
for 유형, color in color_map.items():
    subset = grid[grid['유형'] == 유형]
    subset.plot(ax=ax, color=color, label=유형, alpha=0.7)

gyeongnam.plot(ax=ax, color='none', edgecolor='black', linewidth=1.5)

# 내륙 TOP5 중심점
top5_x = [geom.x for geom in top5_inland['center']]
top5_y = [geom.y for geom in top5_inland['center']]
ax.scatter(top5_x, top5_y, c='blue', s=300, zorder=6, marker='o')

for idx, (x, y) in enumerate(zip(top5_x, top5_y)):
    ax.annotate(f' 후보{idx+1}', xy=(x, y),
                fontsize=13, fontweight='bold', color='navy', zorder=7)

# 시군 이름 표시
for _, row in gyeongnam.iterrows():
    ax.annotate(row['name'],
                xy=(row.geometry.centroid.x, row.geometry.centroid.y),
                fontsize=9, ha='center', color='black', alpha=0.7)

from matplotlib.lines import Line2D
legend_elements = [
    Line2D([0],[0], marker='o', color='w', markerfacecolor='#2ecc71', markersize=12, label='양호지역'),
    Line2D([0],[0], marker='o', color='w', markerfacecolor='#f1c40f', markersize=12, label='보통지역'),
    Line2D([0],[0], marker='o', color='w', markerfacecolor='#e67e22', markersize=12, label='취약지역'),
    Line2D([0],[0], marker='o', color='w', markerfacecolor='#e74c3c', markersize=12, label='최고취약지역'),
    Line2D([0],[0], marker='o', color='w', markerfacecolor='blue', markersize=12, label='최적 입지 후보'),
]
ax.legend(handles=legend_elements, loc='lower left', fontsize=11)
plt.title("경남 야간·휴일 의료기관 최적 입지 후보 TOP5", fontsize=16)
plt.axis('off')
plt.savefig("경남_최적입지.png", dpi=150, bbox_inches='tight')
plt.show()
print("저장완료!")

# 시군별 최고 취약 격자 1개씩 추출
grid_with_city = gpd.sjoin(
    gpd.GeoDataFrame(inland_vulnerable, geometry='center', crs="EPSG:5179"),
    gyeongnam[['name','geometry']],
    how='left', predicate='within'
)

# 시군별 취약도 최고점 1개씩
top_per_city = grid_with_city.groupby('name').apply(
    lambda x: x.nlargest(1, '취약도점수')
).reset_index(drop=True)

# 최고취약지역 시군만
top_vulnerable_cities = top_per_city[
    top_per_city['유형'].isin(['최고취약지역','취약지역'])
].nlargest(5, '취약도점수')

print("시군별 최적 입지 후보:")
print(top_vulnerable_cities[['name','취약도점수','달빛_거리km','심야약국_거리km','유형']].to_string())

# 지도 시각화
fig, ax = plt.subplots(figsize=(12,12))
for 유형, color in color_map.items():
    subset = grid[grid['유형'] == 유형]
    subset.plot(ax=ax, color=color, alpha=0.7)

gyeongnam.plot(ax=ax, color='none', edgecolor='black', linewidth=1.5)

top5_x = [geom.x for geom in top_vulnerable_cities['center']]
top5_y = [geom.y for geom in top_vulnerable_cities['center']]
ax.scatter(top5_x, top5_y, c='blue', s=300, zorder=6)

for idx, (i, row) in enumerate(top_vulnerable_cities.iterrows()):
    ax.annotate(f" {row['name']}",
                xy=(row['center'].x, row['center'].y),
                fontsize=12, fontweight='bold', color='navy', zorder=7)

for _, row in gyeongnam.iterrows():
    ax.annotate(row['name'],
                xy=(row.geometry.centroid.x, row.geometry.centroid.y),
                fontsize=9, ha='center', color='black', alpha=0.7)

from matplotlib.lines import Line2D
legend_elements = [
    Line2D([0],[0], marker='o', color='w', markerfacecolor='#2ecc71', markersize=12, label='양호지역'),
    Line2D([0],[0], marker='o', color='w', markerfacecolor='#f1c40f', markersize=12, label='보통지역'),
    Line2D([0],[0], marker='o', color='w', markerfacecolor='#e67e22', markersize=12, label='취약지역'),
    Line2D([0],[0], marker='o', color='w', markerfacecolor='#e74c3c', markersize=12, label='최고취약지역'),
    Line2D([0],[0], marker='o', color='w', markerfacecolor='blue', markersize=12, label='최적 입지 후보'),
]
ax.legend(handles=legend_elements, loc='lower left', fontsize=11)
plt.title("경남 야간·휴일 의료기관 최적 입지 후보 (시군별 TOP5)", fontsize=16)
plt.axis('off')
plt.savefig("경남_최적입지.png", dpi=150, bbox_inches='tight')
plt.show()
print("저장완료!")

from google.colab import files
files.download("경남_의료기관_지도.png")
files.download("경남_취약도_지도.png")
files.download("경남_전문의_예측.png")
files.download("경남_클러스터_지도.png")
files.download("경남_최적입지.png")